### ISSUE TITLE
HTML document with HTML5 figures 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#130]
Based on this knitr example
https://github.com/yihui/knitr-examples/blob/master/063-html5-figure.Rmd

Basically, it is changing the plot hook. 
```r
knit_hooks$set(plot = function(x, options) {
  paste('<figure><img src="',
        opts_knit$get('base.url'), paste(x, collapse = '.'),
        '"><figcaption>', options$fig.cap, '</figcaption></figure>',
        sep = '')
})
```

Maybe some advance stuff but good to know.

**Comment by dr-harper** [comment]
I am not that familiar with HTML5, so what would the main benefits of this be? This article does provide a comparison of HTML4 and HTML5 for inserting Figures: https://www.w3.org/Style/Examples/007/figures.en.html

This issue is related: https://github.com/yihui/knitr/issues/685 . @yihui mentions that `implicit_figures` provides a potential solution for this. Could you advise @yihui on whether you think this should be mentioned in the book?

Not sure if the `rmarkdown_format` function has anything to do with this: https://www.rdocumentation.org/packages/rmarkdown/versions/1.11/topics/rmarkdown_format

**Comment by yihui** [comment]
Personally I don't see significant benefits of using the HTML5 tags `<figure>` and `<figurecaption>` over the plain old `<div>`.

We should definitely mention the `plot` hook in the book, though. If we cannot think of another application, this one is fine.

**Comment by dr-harper** [comment]
Thanks, I have added this in commit https://github.com/dr-harper/rmarkdown-cookbook/commit/af357840f276fb652b8a69a783c55ba85809f567.

I have provided a basic example of how we could use this in combination with CSS to style the appearance of figures. It is not overly compelling at the moment but I think is an okay starting point.

**Comment by cderv** [comment]
added in 426547d4ec6befad6fa7ffa016a82745901701c0
