### ISSUE TITLE
Tips about the cat engine 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#140]
This knitr example shows a trick to write code to a external file, from a chunk in a Rmd file.
https://github.com/yihui/knitr-examples/blob/master/095-pandoc-header.Rmd

Related to #7

**Comment by cderv** [comment]
@emilyriederer would you describe in more detail your use case regarding the use of `cat` engine following knitr/knitr#1713 ? It believe it could be useful as a recipe in this book and it would be a great addition. Thanks !

**Comment by emilyriederer** [comment]
Definitely! (Sidenote: ohmigoodness this cookbook project! I hadn't heard about it before but 😍 )

My main use case at the moment is writing tutorials or package vignettes that follow the general flow of

> "suppose you have a file that looks like this: {{show file contents}}, you can pass it into this R function like this: {{show R code}}"

However, to achieve this result, I was doing something very awkward.

For example, recently I was writing something to explain how an SQL *script* can be passed to `dbQuery` instead of putting one's whole query in the RMarkdown. To do this, I had to write something like:

````

```{r eval = TRUE, echo = FALSE}
text = "
select isbn, book_title, author_name
from books
where author_name = 'Yihui Xie'
"

f = tempfile(fileext = ".sql") 
writeLines(text, f)
```
Suppose you have the following SQL script saved in `books.sql`:

```{r code = readLines(f), eval = FALSE}
```

Instead of pasting the full script into R, you can read simply read this in dynamically:

```{r}
library(DBI)
f <- fs::path_temp('query.sql') # replace with path to your query.sql script!
data <- dbGetQuery(
              conn = my_db_conn, 
              statement = paste(readLines(f), collapse = " ") 
               )
```
````

This isn't too bad, but it's frustrating to write 6 or so lines of code to manually create a temp file, save my text, and print the context back out when none of that has anything to do with the point I am making. (Hopefully I don't sound *too* lazy 😆 ). 

Also, given that my intended audience might be reading and running the actual RMarkdown interactively (versus just consuming the final output), it was unnecessarily confusing to them to have all that extra code in there and have the ambiguity of whether or not it was part of the "flow" they were supposed to learn / mirror. 

Now that I know about `cat`, I can clean up the above as follows.

````
Suppose you have the following SQL script saved in `books.sql`:

```{cat, engine.opts = list(file = fs::path_temp('books.sql'))}
text = "
select isbn, book_title, author_name
from books
where author_name = 'Yihui Xie'
```
Instead of pasting the full script into R, you can read simply read this in dynamically:

```{r}
library(DBI)
f <- fs::path_temp('query.sql') # replace with path to your query.sql script!
data <- dbGetQuery(
              conn = my_db_conn, 
              statement = paste(readLines(f), collapse = " ") 
               )
```
````

The actual code that pushed me over the edge to file the issue was for work, so I can't share that as-is, but if you want an example with more of a "story" to it, let me know and I can mock something up! 

The kind of process I'm describing is pretty similar to [this vignette](https://emilyriederer.github.io/projmgr/articles/building-custom-plans.html) in my `projmgr` package. It wasn't a problem here because I had the package file-system to work with and needed to save that file in the package anyway. However, I can imagine cases where it would be useful in vignette writing, as well!

**Comment by cderv** [comment]
Thanks for sharing ! 

I spend the afternoon working on adding a chapter on `cat` engine. I covered the issue we discussed about using yaml as example. I think it is close to what you described.

When a first version will be merged (after @dr-harper  review), you should have a look and see if you have idea for new example. You can also have a look to the PR and make suggestions. 

Thanks @emilyriederer ! 

> (Sidenote: ohmigoodness this cookbook project! I hadn't heard about it before but 😍 )

This is a project that has been around for a few months now. we are going slowly but plan to cover a lot. Every ideas are in issues. It nice to know people find it useful ! 😄

**Comment by cderv** [comment]
This is covered by #167 and so we can close.

**Comment by cderv** [comment]
Covered in b2219341b124009d2c62c4b7f5f6485af0c61376
